<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PesanansSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('pesanans')->insert([
            [
                'id' => 1,
                'user_id' => 6,
                'walkin_customer_id' => null,
                'mitra_id' => 1,
                'jenis_pesanan' => 'Kiloan',
                'catatan_pesanan' => 'Cuci bersih',
                'tipe_dp_wajib' => 'Ya',
                'tipe_bisa_lunas' => 'tidak',
                'tanggal_pesan' => '2025-07-20',
                'opsi_jemput' => 'Ya',
                'jadwal_jemput' => '2025-07-20 09:00:00',
                'opsi_antar' => 'Ya',
                'jadwal_antar' => '2025-07-22 14:00:00',
                'catatan_pengiriman' => 'Antar ke rumah',
                'created_at' => '2025-07-20 08:00:00',
                'updated_at' => '2025-07-20 08:00:00',
            ],
            [
                'id' => 2,
                'user_id' => 7,
                'walkin_customer_id' => null,
                'mitra_id' => 1,
                'jenis_pesanan' => 'Kiloan + Satuan',
                'catatan_pesanan' => 'Cuci hati-hati',
                'tipe_dp_wajib' => 'Ya',
                'tipe_bisa_lunas' => 'tidak',
                'tanggal_pesan' => '2025-07-21',
                'opsi_jemput' => 'Ya',
                'jadwal_jemput' => '2025-07-21 10:00:00',
                'opsi_antar' => 'Ya',
                'jadwal_antar' => '2025-07-24 15:00:00',
                'catatan_pengiriman' => 'Antar ke rumah',
                'created_at' => '2025-07-21 09:00:00',
                'updated_at' => '2025-07-21 09:00:00',
            ],
            [
                'id' => 3,
                'user_id' => 8,
                'walkin_customer_id' => null,
                'mitra_id' => 2,
                'jenis_pesanan' => 'Kiloan',
                'catatan_pesanan' => 'Cuci standar',
                'tipe_dp_wajib' => 'Ya',
                'tipe_bisa_lunas' => 'tidak',
                'tanggal_pesan' => '2025-07-21',
                'opsi_jemput' => 'Ya',
                'jadwal_jemput' => '2025-07-21 10:00:00',
                'opsi_antar' => 'Tidak',
                'jadwal_antar' => null,
                'catatan_pengiriman' => 'Ambil di toko',
                'created_at' => '2025-07-21 04:34:00',
                'updated_at' => '2025-07-21 04:34:00',
            ],
            [
                'id' => 4,
                'user_id' => 9,
                'walkin_customer_id' => null,
                'mitra_id' => 3,
                'jenis_pesanan' => 'Satuan',
                'catatan_pesanan' => 'Cuci hati-hati',
                'tipe_dp_wajib' => 'Tidak',
                'tipe_bisa_lunas' => 'Ya',
                'tanggal_pesan' => '2025-07-21',
                'opsi_jemput' => 'Ya',
                'jadwal_jemput' => '2025-07-21 10:00:00',
                'opsi_antar' => 'Ya',
                'jadwal_antar' => '2025-07-23 14:00:00',
                'catatan_pengiriman' => 'Antar ke rumah',
                'created_at' => '2025-07-21 04:43:00',
                'updated_at' => '2025-07-21 04:43:00',
            ],
            [
                'id' => 5,
                'user_id' => 10,
                'walkin_customer_id' => null,
                'mitra_id' => 1,
                'jenis_pesanan' => 'Kiloan + Satuan',
                'catatan_pesanan' => 'Cuci hati-hati',
                'tipe_dp_wajib' => 'Ya',
                'tipe_bisa_lunas' => 'tidak',
                'tanggal_pesan' => '2025-07-21',
                'opsi_jemput' => 'Tidak',
                'jadwal_jemput' => null,
                'opsi_antar' => 'Ya',
                'jadwal_antar' => '2025-07-24 14:00:00',
                'catatan_pengiriman' => 'Antar ke rumah',
                'created_at' => '2025-07-21 04:59:00',
                'updated_at' => '2025-07-24 14:30:00',
            ],
            [
                'id' => 6,
                'user_id' => null,
                'walkin_customer_id' => 1,
                'mitra_id' => 1,
                'jenis_pesanan' => 'Satuan',
                'catatan_pesanan' => 'Cuci hati-hati',
                'tipe_dp_wajib' => 'Tidak',
                'tipe_bisa_lunas' => 'Ya',
                'tanggal_pesan' => '2025-07-21',
                'opsi_jemput' => 'Tidak',
                'jadwal_jemput' => null,
                'opsi_antar' => 'Tidak',
                'jadwal_antar' => null,
                'catatan_pengiriman' => 'Ambil di toko',
                'created_at' => '2025-07-21 05:07:00',
                'updated_at' => '2025-07-24 14:30:00',
            ],
            [
                'id' => 7,
                'user_id' => null,
                'walkin_customer_id' => 2,
                'mitra_id' => 1,
                'jenis_pesanan' => 'Kiloan + Satuan',
                'catatan_pesanan' => 'Cuci hati-hati',
                'tipe_dp_wajib' => 'Ya',
                'tipe_bisa_lunas' => 'tidak',
                'tanggal_pesan' => '2025-07-21',
                'opsi_jemput' => 'Tidak',
                'jadwal_jemput' => null,
                'opsi_antar' => 'Ya',
                'jadwal_antar' => '2025-07-24 15:00:00',
                'catatan_pengiriman' => 'Antar ke rumah',
                'created_at' => '2025-07-21 05:14:00',
                'updated_at' => '2025-07-24 15:30:00',
            ],
            [
                'id' => 8,
                'user_id' => null,
                'walkin_customer_id' => 3,
                'mitra_id' => 3,
                'jenis_pesanan' => 'Kiloan',
                'catatan_pesanan' => 'Cuci cepat',
                'tipe_dp_wajib' => 'Ya',
                'tipe_bisa_lunas' => 'tidak',
                'tanggal_pesan' => '2025-07-21',
                'opsi_jemput' => 'Tidak',
                'jadwal_jemput' => null,
                'opsi_antar' => 'Tidak',
                'jadwal_antar' => null,
                'catatan_pengiriman' => 'Ambil di toko',
                'created_at' => '2025-07-21 05:27:00',
                'updated_at' => '2025-07-22 14:30:00',
            ],
            [
                'id' => 9,
                'user_id' => 17,
                'walkin_customer_id' => null,
                'mitra_id' => 1,
                'jenis_pesanan' => 'kiloan',
                'catatan_pesanan' => 'Cuci cepat',
                'tipe_dp_wajib' => 'Tidak',
                'tipe_bisa_lunas' => 'Ya',
                'tanggal_pesan' => '2025-07-22',
                'opsi_jemput' => 'Tidak',
                'jadwal_jemput' => null,
                'opsi_antar' => 'Ya',
                'jadwal_antar' => '2025-07-23 14:00:00',
                'catatan_pengiriman' => 'Antar ke rumah',
                'created_at' => '2025-07-22 17:27:00',
                'updated_at' => '2025-07-22 17:36:00',
            ],
            [
                'id' => 10,
                'user_id' => 18,
                'walkin_customer_id' => null,
                'mitra_id' => 1,
                'jenis_pesanan' => 'satuan',
                'catatan_pesanan' => 'Cuci hati-hati',
                'tipe_dp_wajib' => 'Ya',
                'tipe_bisa_lunas' => 'Ya',
                'tanggal_pesan' => '2025-07-22',
                'opsi_jemput' => 'Tidak',
                'jadwal_jemput' => null,
                'opsi_antar' => 'Tidak',
                'jadwal_antar' => null,
                'catatan_pengiriman' => 'Ambil di toko',
                'created_at' => '2025-07-22 17:39:00',
                'updated_at' => '2025-07-22 17:39:00',
            ],
            [
                'id' => 11,
                'user_id' => 19,
                'walkin_customer_id' => null,
                'mitra_id' => 1,
                'jenis_pesanan' => 'gabungan',
                'catatan_pesanan' => 'Cuci standar',
                'tipe_dp_wajib' => 'Tidak',
                'tipe_bisa_lunas' => 'Ya',
                'tanggal_pesan' => '2025-07-22',
                'opsi_jemput' => 'Tidak',
                'jadwal_jemput' => null,
                'opsi_antar' => 'Tidak',
                'jadwal_antar' => null,
                'catatan_pengiriman' => 'Ambil di toko',
                'created_at' => '2025-07-22 17:53:00',
                'updated_at' => '2025-07-22 17:53:00',
            ],
        ]);
    }
}
